make: proj1_init proj1_shutdown proj1_create proj1_destroy proj1_count proj1_send proj1_recv proj1_length proj1_acl_add proj1_acl_remove proj1_nolist proj1_notroot proj1_notexist

proj1_init: proj1_init.c
		gcc -o proj1_init proj1_init.c

proj1_shutdown: proj1_shutdown.c
		gcc -o proj1_shutdown proj1_shutdown.c

proj1_create: proj1_create.c
		gcc -o proj1_create proj1_create.c

proj1_destroy: proj1_destroy.c
		gcc -o proj1_destroy proj1_destroy.c

proj1_count: proj1_count.c
		gcc -o proj1_count proj1_count.c

proj1_send: proj1_send.c
		gcc -o proj1_send proj1_send.c

proj1_recv: proj1_recv.c
		gcc -o proj1_recv proj1_recv.c

proj1_length: proj1_length.c
		gcc -o proj1_length proj1_length.c

proj1_acl_add: proj1_acl_add.c
		gcc -o proj1_acl_add proj1_acl_add.c

proj1_acl_remove: proj1_acl_remove.c
		gcc -o proj1_acl_remove proj1_acl_remove.c

proj1_nolist: proj1_nolist.c
		gcc -o proj1_nolist proj1_nolist.c

proj1_notroot: proj1_notroot.c
		gcc -o proj1_notroot proj1_notroot.c

proj1_notexist: proj1_notexist.c
		gcc -o proj1_notexist proj1_notexist.c
