make: sbx421_block sbx421_unblock sbx421_count sbx421_run sbx421_shutdown

sbx421_block: sbx421_block.c
	gcc -o sbx421_block sbx421_block.c

sbx421_unblock: sbx421_unblock.c
	gcc -o sbx421_unblock sbx421_unblock.c

sbx421_count: sbx421_count.c
	gcc -o sbx421_count sbx421_count.c

sbx421_run: sbx421_run.c
	gcc -o sbx421_run sbx421_run.c

sbx421_shutdown: sbx421_shutdown.c
	gcc -o sbx421_shutdown sbx421_shutdown.c

clean:
	rm *~
